app:
  defaultLanguage: en
  supportedLanguages: de,en,hr,sv,pl,es,is,fr,nb,cs
server:
  port: 8080
  servlet:
    context-path: /RMBTMapServer
spring:
  application:
    name: map-backend
  datasource:
    poolSize: 20
    minIdle: 1
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${MAP_DB_HOST}:${MAP_DB_PORT}/${MAP_DB_NAME}
    username: ${MAP_DB_USER}
    password: ${MAP_DB_PASSWORD}

  #    tomcat:
  #      test-while-idle: true
  #      test-on-borrow: true
  #      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    deserialization:
      fail-on-unknown-properties: true
redis:
  host: ${MAP_REDIS_HOST}
  port: ${MAP_REDIS_PORT}
java:
  util:
    PropertyResourceBundle:
      encoding:UTF-8
application-version:
  host: rtr-api-dev

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    poolSize: 20
    minIdle: 1
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${MAP_DB_HOST}:${MAP_DB_PORT}/${MAP_DB_NAME}
    username: ${MAP_DB_USER}
    password: ${MAP_DB_PASSWORD}
    tomcat:
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1

application-version:
  host: ${HOST_ID}

redis:
  host: ${MAP_REDIS_HOST}
  port: ${MAP_REDIS_PORT}
logging:
  config: ${LOGGING_CONFIG_FILE_MAP:classpath:logback.xml}